name: Check PHP syntax

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', 'highest']
    steps:
      # Install PHP interpreter
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-file: development

      # Checkout source repository
      - name: checkout repo
        uses: actions/checkout@v3

      # Lint every PHP source file using PHP interpreter
      - run: composer run check-syntax
