name: PHP
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: highest
          tools: composer
      - run: composer run-script check-syntax
      - run: composer install --no-progress
      - run: composer run-script check-codestyle
      - run: composer run-script static-analysis
      - run: composer run-script test
      - run: php tests/benchmarks/run.php
