name: PHP
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Install dependencies
        run: composer install --no-progress
      - name: Run test suite
        run: composer run-script test
      - name: Run codestyle sniffer
        run: composer run-script codestyle
